// Generado por tools/build-knowledge.mjs desde content/conocimiento/*.md: no editar a mano.
// GROUPS: texto de cada grupo para el prompt de la IA. GROUP_BY_SPECIES: especie aceptada o género → grupo. GROUP_BY_NAME: nombre común (sin tildes) → grupo.
export const KNOWLEDGE_VERSION = "2026-10-09";
export const GROUPS = {
  "arbustos-de-flor": {
    "nombre": "Arbustos y plantas de flor en jardín o maceta",
    "updated": "2026-10-09",
    "text": "Grupo: Arbustos y plantas de flor en jardín o maceta (pautas pensadas para: Mediterráneo y templado, hemisferio norte).\nPrimavera: Poda principal en las que lo piden, abonado para floración y riego creciente.\nVerano: Riego regular (más en maceta); retirar flores marchitas; Abono rico en potasio mejor que en nitrógeno para florecer.\nOtoño: Reducir riego y dejar de abonar; si abonas, poco nitrógeno y más fósforo y potasio; No podar fuerte: muchas ya llevan las yemas de la flor del año que viene (hortensia, jazmín); Retirar hojas y flores secas del pie y de la maceta para evitar hongos con la humedad; Quitar el plato; preparar protección en las sensibles al frío.\nInvierno: Riego mínimo; proteger las sensibles a las heladas.\nErrores comunes: Mucho nitrógeno: hojas y pocas flores; Dejar restos secos pegados a la planta."
  },
  "citricos": {
    "nombre": "Cítricos y frutales en maceta",
    "updated": "2026-10-09",
    "text": "Grupo: Cítricos y frutales en maceta (pautas pensadas para: Mediterráneo y templado, hemisferio norte).\nPrimavera: Poda ligera tras la cosecha o a final del invierno; abonado para cítricos; Riego regular sin encharcar.\nVerano: Riego frecuente en maceta; abonado cada pocas semanas; Vigila pulgones y cochinilla.\nOtoño: Muchos tienen ya flores y frutos del año que viene: evita podas fuertes o te quedas sin cosecha; Si abonas, que sea con poco nitrógeno y más fósforo y potasio: el nitrógeno provoca brotes tiernos que el frío quema; Quita los platos y reduce el riego poco a poco; No trasplantes plantas que están floreciendo o cuajando fruto; Prepara la protección: sensibles a las heladas.\nInvierno: Riego escaso; protegerlos de heladas (tela antiheladas o sitio resguardado).\nErrores comunes: Podar fuerte en otoño; Abonar con mucho nitrógeno tarde; Encharcar el plato."
  },
  "huerto": {
    "nombre": "Huerto urbano",
    "updated": "2026-10-09",
    "text": "Grupo: Huerto urbano (pautas pensadas para: Mediterráneo y templado, hemisferio norte).\nPrimavera: Siembra y trasplante de cultivos de verano.\nVerano: Riego frecuente, acolchado y cosecha continua.\nOtoño: Retirar los cultivos de verano agotados y preparar el suelo; Empezar la fase de otoño-invierno (hoja, raíces, ajos…); algunas aromáticas aguantan aún unas semanas.\nInvierno: Cultivos de invierno; proteger de heladas.\nErrores comunes: Dejar restos de cultivo enfermo en el suelo."
  },
  "interior": {
    "nombre": "Plantas de interior",
    "updated": "2026-10-09",
    "text": "Grupo: Plantas de interior (pautas pensadas para: Cualquiera; dentro de casa la temperatura es estable).\nPrimavera: Trasplante y abonado de inicio; el riego sube con la luz.\nVerano: Luz filtrada; si estaban fuera, que no reciban sol directo fuerte; Más riego, pero siempre comprobando el sustrato.\nOtoño: Entra las que estaban fuera antes de que las noches bajen de unos 10–15 °C; Riego: en otoño cuenta más la cantidad que los días. Como mucho una vez por semana y con poca agua: sustrato húmedo, no empapado; Hojas medio amarillas y medio verdes suelen indicar exceso de agua; Menos abono; quita el plato con agua.\nInvierno: Riego mínimo, lejos de corrientes y de la calefacción; Luz máxima: cerca de la ventana.\nErrores comunes: Sustrato mojado durante muchos días; Agua acumulada en el plato; Mover la planta de sitio a menudo."
  },
  "mediterraneas": {
    "nombre": "Mediterráneas de sol y poco riego",
    "updated": "2026-10-09",
    "text": "Grupo: Mediterráneas de sol y poco riego (pautas pensadas para: Mediterráneo y templado, hemisferio norte).\nPrimavera: Poda de formación (olivo) y plantación; abono muy suave o ninguno.\nVerano: Sol pleno, poco riego; en maceta, algo más; Poda ligera de lavanda y romero tras la floración, sin cortar la madera vieja.\nOtoño: Riego mínimo: les sobra la humedad; en maceta, quita el plato; Buen momento para plantarlas en suelo en climas suaves; No abonar y no podar a fondo; despuntar solo los brotes largos del verano en las resistentes.\nInvierno: Casi sin riego; en maceta, protegerlas en heladas fuertes.\nErrores comunes: Regar de más y abonar; Cortar madera vieja sin hojas (no rebrota)."
  },
  "suculentas": {
    "nombre": "Suculentas y cactus",
    "updated": "2026-10-09",
    "text": "Grupo: Suculentas y cactus (pautas pensadas para: Mediterráneo y templado, hemisferio norte).\nPrimavera: Mejor momento para trasplantar, hacer esquejes y dar el primer abono suave; El riego sube poco a poco; siempre con el sustrato seco entre riegos.\nVerano: Sol con precaución: las que vienen de sombra se queman si pasan de golpe a sol directo; Riego espaciado y de noche o de mañana; en maceta, con drenaje.\nOtoño: Los últimos riegos del año se dan ya: con el frío casi paran de crecer; Si pasan el invierno fuera, ponlas a pleno sol pero resguardadas de la lluvia; No trasplantar las que van a estar fuera; las de interior o una emergencia sí; Mejor guardar en interior las sensibles (sansevieria) antes de que llegue un descenso brusco de temperatura.\nInvierno: Casi sin riego durante meses (o nada) si hace frío; la humedad con frío pudre; Mucha luz; evitar corrientes y calefacción directa.\nErrores comunes: Regar «por calendario» en vez de comprobar el sustrato; Dejar agua en el plato; Seguir regando en otoño como en verano."
  }
};
export const GROUP_BY_SPECIES = {
  "abelia": "arbustos-de-flor",
  "aeonium": "suculentas",
  "agave": "suculentas",
  "aglaonema": "interior",
  "allium": "huerto",
  "aloe": "suculentas",
  "anthurium": "interior",
  "aspidistra": "interior",
  "bougainvillea": "arbustos-de-flor",
  "calathea": "interior",
  "calendula": "huerto",
  "camellia": "arbustos-de-flor",
  "capsicum": "huerto",
  "chlorophytum": "interior",
  "citrofortunella": "citricos",
  "citrus": "citricos",
  "crassula": "suculentas",
  "cucumis": "huerto",
  "cucurbita": "huerto",
  "dieffenbachia": "interior",
  "dracaena fragrans": "interior",
  "dracaena marginata": "interior",
  "dracaena trifasciata": "suculentas",
  "echeveria": "suculentas",
  "echinocactus": "suculentas",
  "echinopsis": "suculentas",
  "epipremnum": "interior",
  "ficus benjamina": "interior",
  "ficus elastica": "interior",
  "ficus lyrata": "interior",
  "fortunella": "citricos",
  "fragaria": "huerto",
  "gardenia": "arbustos-de-flor",
  "goeppertia": "interior",
  "graptopetalum": "suculentas",
  "haworthia": "suculentas",
  "haworthiopsis": "suculentas",
  "helichrysum": "mediterraneas",
  "hibiscus": "arbustos-de-flor",
  "hydrangea": "arbustos-de-flor",
  "jasminum": "arbustos-de-flor",
  "kalanchoe": "suculentas",
  "lactuca": "huerto",
  "lantana": "arbustos-de-flor",
  "lavandula": "mediterraneas",
  "mammillaria": "suculentas",
  "maranta": "interior",
  "mentha": "huerto",
  "monstera": "interior",
  "nerium oleander": "arbustos-de-flor",
  "ocimum": "huerto",
  "olea europaea": "mediterraneas",
  "opuntia": "suculentas",
  "pelargonium": "arbustos-de-flor",
  "peperomia": "interior",
  "petroselinum": "huerto",
  "phalaenopsis": "interior",
  "phaseolus": "huerto",
  "philodendron": "interior",
  "pilea": "interior",
  "plumbago": "arbustos-de-flor",
  "polygala": "arbustos-de-flor",
  "rhododendron": "arbustos-de-flor",
  "rosa": "arbustos-de-flor",
  "salvia rosmarinus": "mediterraneas",
  "sansevieria": "suculentas",
  "santolina": "mediterraneas",
  "sedum": "suculentas",
  "sempervivum": "suculentas",
  "solanum lycopersicum": "huerto",
  "spathiphyllum": "interior",
  "spinacia": "huerto",
  "strelitzia nicolai": "interior",
  "thymus": "mediterraneas",
  "trachelospermum": "arbustos-de-flor",
  "zamioculcas": "interior"
};
export const GROUP_BY_NAME = {
  "adelfa": "arbustos-de-flor",
  "agave": "suculentas",
  "aglaonema": "interior",
  "ajo": "huerto",
  "albahaca": "huerto",
  "aloe": "suculentas",
  "aloe vera": "suculentas",
  "anturio": "interior",
  "arbol de jade": "suculentas",
  "aspidistra": "interior",
  "azalea": "arbustos-de-flor",
  "buganvilla": "arbustos-de-flor",
  "cactus": "suculentas",
  "calabacin": "huerto",
  "calamondin": "citricos",
  "calathea": "interior",
  "calendula": "huerto",
  "camelia": "arbustos-de-flor",
  "cantueso": "mediterraneas",
  "cebolla": "huerto",
  "chumbera": "suculentas",
  "cinta": "interior",
  "citrico": "citricos",
  "costilla de adan": "interior",
  "crasa": "suculentas",
  "difenbachia": "interior",
  "echeveria": "suculentas",
  "espatifilo": "interior",
  "espinaca": "huerto",
  "espliego": "mediterraneas",
  "falso jazmin": "arbustos-de-flor",
  "ficus": "interior",
  "fresa": "huerto",
  "fresal": "huerto",
  "gardenia": "arbustos-de-flor",
  "geranio": "arbustos-de-flor",
  "gitanilla": "arbustos-de-flor",
  "guindilla": "huerto",
  "hibisco": "arbustos-de-flor",
  "hierbabuena": "huerto",
  "hortensia": "arbustos-de-flor",
  "jade": "suculentas",
  "jazmin": "arbustos-de-flor",
  "judia": "huerto",
  "kalanchoe": "suculentas",
  "kumquat": "citricos",
  "lantana": "arbustos-de-flor",
  "lavanda": "mediterraneas",
  "lechuga": "huerto",
  "lengua de suegra": "suculentas",
  "lima": "citricos",
  "limero": "citricos",
  "limon": "citricos",
  "limonero": "citricos",
  "mandarino": "citricos",
  "maranta": "interior",
  "menta": "huerto",
  "monstera": "interior",
  "naranjo": "citricos",
  "nopal": "suculentas",
  "olivo": "mediterraneas",
  "orquidea": "interior",
  "peperomia": "interior",
  "pepino": "huerto",
  "perejil": "huerto",
  "pilea": "interior",
  "pimiento": "huerto",
  "plumbago": "arbustos-de-flor",
  "pomelo": "citricos",
  "pothos": "interior",
  "potos": "interior",
  "puerro": "huerto",
  "romero": "mediterraneas",
  "rosal": "arbustos-de-flor",
  "sansevieria": "suculentas",
  "santolina": "mediterraneas",
  "siempreviva": "suculentas",
  "suculenta": "suculentas",
  "tomate": "huerto",
  "tomatera": "huerto",
  "tomatero": "huerto",
  "tomillo": "mediterraneas",
  "zamioculca": "interior"
};
