// Generado por tools/build-species-seed.mjs desde content/referencia/plantas.json: no editar a mano.
// SYNONYMS: nombre científico antiguo o alternativo → especie aceptada. ALIASES: nombre común (sin tildes) → especie.
export const SYNONYMS = {
  "aloe barbadensis": "aloe vera",
  "bougainvillea spectabilis": "bougainvillea glabra",
  "crassula argentea": "crassula ovata",
  "crassula portulacea": "crassula ovata",
  "lavandula intermedia": "lavandula angustifolia",
  "lavandula stoechas": "lavandula angustifolia",
  "lycopersicon esculentum": "solanum lycopersicum",
  "pelargonium peltatum": "pelargonium hortorum",
  "pelargonium zonale": "pelargonium hortorum",
  "phalaenopsis amabilis": "phalaenopsis",
  "phalaenopsis hybrid": "phalaenopsis",
  "rosa hybrida": "rosa",
  "rosmarinus officinalis": "salvia rosmarinus",
  "sansevieria trifasciata": "dracaena trifasciata",
  "scindapsus aureus": "epipremnum aureum"
};
export const ALIASES = {
  "adelfa": "nerium oleander",
  "albahaca": "ocimum basilicum",
  "aloe": "aloe vera",
  "aloe vera": "aloe vera",
  "arbol de jade": "crassula ovata",
  "baladre": "nerium oleander",
  "basilico": "ocimum basilicum",
  "bougainvillea glabra": "bougainvillea glabra",
  "bugambilia": "bougainvillea glabra",
  "buganvilla": "bougainvillea glabra",
  "cantueso": "lavandula angustifolia",
  "citrus limon": "citrus limon",
  "costilla de adan": "monstera deliciosa",
  "crassula ovata": "crassula ovata",
  "crasula": "crassula ovata",
  "dracaena trifasciata": "dracaena trifasciata",
  "epipremnum": "epipremnum aureum",
  "epipremnum aureum": "epipremnum aureum",
  "espada de san jorge": "dracaena trifasciata",
  "espliego": "lavandula angustifolia",
  "falso jazmin": "trachelospermum jasminoides",
  "ficus benjamina": "ficus benjamina",
  "ficus de interior": "ficus benjamina",
  "geranio": "pelargonium hortorum",
  "geranio de balcon": "pelargonium hortorum",
  "hierbabuena": "mentha spicata",
  "hortensia": "hydrangea macrophylla",
  "hydrangea macrophylla": "hydrangea macrophylla",
  "jazmin estrellado": "trachelospermum jasminoides",
  "lavanda": "lavandula angustifolia",
  "lavandula angustifolia": "lavandula angustifolia",
  "lengua de suegra": "dracaena trifasciata",
  "lengua de tigre": "dracaena trifasciata",
  "limon": "citrus limon",
  "limonero": "citrus limon",
  "limonero en maceta": "citrus limon",
  "menta verde": "mentha spicata",
  "mentha spicata": "mentha spicata",
  "monstera": "monstera deliciosa",
  "monstera deliciosa": "monstera deliciosa",
  "nerium oleander": "nerium oleander",
  "ocimum basilicum": "ocimum basilicum",
  "olea europaea": "olea europaea",
  "oleandro": "nerium oleander",
  "olivera": "olea europaea",
  "olivo": "olea europaea",
  "olivo ornamental": "olea europaea",
  "orquidea mariposa": "phalaenopsis",
  "orquidea phalaenopsis": "phalaenopsis",
  "pelargonio": "pelargonium hortorum",
  "pelargonium hortorum": "pelargonium hortorum",
  "phalaenopsis": "phalaenopsis",
  "planta de tomate": "solanum lycopersicum",
  "planta del diablo": "epipremnum aureum",
  "planta del dinero": "crassula ovata",
  "pothos": "epipremnum aureum",
  "poto": "epipremnum aureum",
  "potos": "epipremnum aureum",
  "romero": "salvia rosmarinus",
  "rosa": "rosa",
  "rosal": "rosa",
  "rosal arbustivo": "rosa",
  "rosmarinus": "salvia rosmarinus",
  "sabila": "aloe vera",
  "salvia rosmarinus": "salvia rosmarinus",
  "sansevieria": "dracaena trifasciata",
  "solanum lycopersicum": "solanum lycopersicum",
  "tomate": "solanum lycopersicum",
  "tomatera": "solanum lycopersicum",
  "tomatero": "solanum lycopersicum",
  "trachelospermum": "trachelospermum jasminoides",
  "trachelospermum jasminoides": "trachelospermum jasminoides",
  "trinitaria": "bougainvillea glabra"
};
