// Generado por tools/build-species-seed.mjs desde content/referencia/plantas.json: no editar a mano.
// SYNONYMS: nombre científico antiguo o alternativo → especie aceptada. ALIASES: nombre común (sin tildes) → especie.
export const SYNONYMS = {
  "aloe barbadensis": "aloe vera",
  "bougainvillea spectabilis": "bougainvillea glabra",
  "crassula argentea": "crassula ovata",
  "crassula portulacea": "crassula ovata",
  "lavandula intermedia": "lavandula angustifolia",
  "lavandula stoechas": "lavandula angustifolia",
  "lycopersicon esculentum": "solanum lycopersicum",
  "pelargonium peltatum": "pelargonium hortorum",
  "pelargonium zonale": "pelargonium hortorum",
  "pennisetum advena": "pennisetum setaceum",
  "phalaenopsis amabilis": "phalaenopsis",
  "phalaenopsis hybrid": "phalaenopsis",
  "rosa hybrida": "rosa",
  "rosmarinus officinalis": "salvia rosmarinus",
  "sansevieria trifasciata": "dracaena trifasciata",
  "scindapsus aureus": "epipremnum aureum",
  "sedum spectabile": "hylotelephium spectabile",
  "senecio cineraria": "jacobaea maritima"
};
export const ALIASES = {
  "abelia": "abelia grandiflora",
  "abelia grandiflora": "abelia grandiflora",
  "adelfa": "nerium oleander",
  "agapanthus": "agapanthus",
  "agapanto": "agapanthus",
  "albahaca": "ocimum basilicum",
  "aligustre": "ligustrum",
  "aloe": "aloe vera",
  "aloe vera": "aloe vera",
  "anemona japonesa": "anemone hybrida",
  "anemone hybrida": "anemone hybrida",
  "arbol de jade": "crassula ovata",
  "arbol de las pelucas": "cotinus coggygria",
  "aster": "aster",
  "baladre": "nerium oleander",
  "bambu sagrado": "nandina domestica",
  "basilico": "ocimum basilicum",
  "berberis": "berberis thunbergii",
  "berberis thunbergii": "berberis thunbergii",
  "bonetero del japon": "euonymus japonicus",
  "bougainvillea glabra": "bougainvillea glabra",
  "bugambilia": "bougainvillea glabra",
  "buganvilla": "bougainvillea glabra",
  "calicarpa": "callicarpa bodinieri",
  "callicarpa": "callicarpa bodinieri",
  "callicarpa bodinieri": "callicarpa bodinieri",
  "camelia de otono": "camellia sasanqua",
  "camellia sasanqua": "camellia sasanqua",
  "cantueso": "lavandula angustifolia",
  "cineraria maritima": "jacobaea maritima",
  "citrus limon": "citrus limon",
  "costilla de adan": "monstera deliciosa",
  "cotinus": "cotinus coggygria",
  "cotinus coggygria": "cotinus coggygria",
  "crassula ovata": "crassula ovata",
  "crasula": "crassula ovata",
  "dimorfoteca": "dimorphotheca",
  "dimorphotheca": "dimorphotheca",
  "dracaena trifasciata": "dracaena trifasciata",
  "durillo": "viburnum tinus",
  "elaeagnus": "elaeagnus",
  "eleagno": "elaeagnus",
  "eleagnus": "elaeagnus",
  "epipremnum": "epipremnum aureum",
  "epipremnum aureum": "epipremnum aureum",
  "escallonia rubra": "escallonia rubra",
  "escalonia": "escallonia rubra",
  "espada de san jorge": "dracaena trifasciata",
  "espino de fuego": "pyracantha",
  "espliego": "lavandula angustifolia",
  "euonymus japonicus": "euonymus japonicus",
  "evonimo": "euonymus japonicus",
  "falso curry": "helichrysum italicum",
  "falso jazmin": "trachelospermum jasminoides",
  "ficus benjamina": "ficus benjamina",
  "ficus de interior": "ficus benjamina",
  "fotinia": "photinia fraseri",
  "fotinia red robin": "photinia fraseri",
  "geranio": "pelargonium hortorum",
  "geranio de balcon": "pelargonium hortorum",
  "hedera helix": "hedera helix",
  "helichrysum italicum": "helichrysum italicum",
  "hiedra": "hedera helix",
  "hierbabuena": "mentha spicata",
  "hortensia": "hydrangea macrophylla",
  "hydrangea macrophylla": "hydrangea macrophylla",
  "hylotelephium spectabile": "hylotelephium spectabile",
  "jacobaea maritima": "jacobaea maritima",
  "jazmin estrellado": "trachelospermum jasminoides",
  "laurel comun": "laurus nobilis",
  "laurel de cocina": "laurus nobilis",
  "laurus nobilis": "laurus nobilis",
  "lavanda": "lavandula angustifolia",
  "lavandula angustifolia": "lavandula angustifolia",
  "lengua de suegra": "dracaena trifasciata",
  "lengua de tigre": "dracaena trifasciata",
  "ligustrum": "ligustrum",
  "limon": "citrus limon",
  "limonero": "citrus limon",
  "limonero en maceta": "citrus limon",
  "liquidambar": "liquidambar styraciflua",
  "liquidambar styraciflua": "liquidambar styraciflua",
  "lonicera": "lonicera",
  "madreselva": "lonicera",
  "menta verde": "mentha spicata",
  "mentha spicata": "mentha spicata",
  "monstera": "monstera deliciosa",
  "monstera deliciosa": "monstera deliciosa",
  "nandina": "nandina domestica",
  "nandina domestica": "nandina domestica",
  "nerine": "nerine bowdenii",
  "nerine bowdenii": "nerine bowdenii",
  "nerium oleander": "nerium oleander",
  "ocimum basilicum": "ocimum basilicum",
  "olea europaea": "olea europaea",
  "oleandro": "nerium oleander",
  "olivera": "olea europaea",
  "olivilla": "teucrium fruticans",
  "olivo": "olea europaea",
  "olivo ornamental": "olea europaea",
  "orquidea mariposa": "phalaenopsis",
  "orquidea phalaenopsis": "phalaenopsis",
  "pelargonio": "pelargonium hortorum",
  "pelargonium hortorum": "pelargonium hortorum",
  "pennisetum rojo": "pennisetum setaceum",
  "pennisetum rubrum": "pennisetum setaceum",
  "pennisetum setaceum": "pennisetum setaceum",
  "phalaenopsis": "phalaenopsis",
  "photinia fraseri": "photinia fraseri",
  "photinia red robin": "photinia fraseri",
  "piracanta": "pyracantha",
  "pitosporo": "pittosporum tobira",
  "pitosporum": "pittosporum tobira",
  "pittosporum tobira": "pittosporum tobira",
  "planta de tomate": "solanum lycopersicum",
  "planta del curry": "helichrysum italicum",
  "planta del diablo": "epipremnum aureum",
  "planta del dinero": "crassula ovata",
  "pothos": "epipremnum aureum",
  "poto": "epipremnum aureum",
  "potos": "epipremnum aureum",
  "pyracantha": "pyracantha",
  "romero": "salvia rosmarinus",
  "rosa": "rosa",
  "rosal": "rosa",
  "rosal arbustivo": "rosa",
  "rosmarinus": "salvia rosmarinus",
  "sabila": "aloe vera",
  "salvia arbustiva": "salvia greggii",
  "salvia greggii": "salvia greggii",
  "salvia rosmarinus": "salvia rosmarinus",
  "sansevieria": "dracaena trifasciata",
  "santolina": "santolina chamaecyparissus",
  "santolina chamaecyparissus": "santolina chamaecyparissus",
  "sedum espectable": "hylotelephium spectabile",
  "sedum spectabile": "hylotelephium spectabile",
  "senecio cineraria": "jacobaea maritima",
  "solanum lycopersicum": "solanum lycopersicum",
  "teucrium fruticans": "teucrium fruticans",
  "thuja occidentalis": "thuja occidentalis",
  "thymus vulgaris": "thymus vulgaris",
  "tomate": "solanum lycopersicum",
  "tomatera": "solanum lycopersicum",
  "tomatero": "solanum lycopersicum",
  "tomillo": "thymus vulgaris",
  "trachelospermum": "trachelospermum jasminoides",
  "trachelospermum jasminoides": "trachelospermum jasminoides",
  "trinitaria": "bougainvillea glabra",
  "tuya": "thuja occidentalis",
  "tuya occidental": "thuja occidentalis",
  "verbena bonariensis": "verbena bonariensis",
  "verbena de buenos aires": "verbena bonariensis",
  "viburnum tinus": "viburnum tinus"
};
